from tkinter import *
from tkinter import messagebox
def kfco(event):
    messagebox.showinfo(title="เซนเตอร์ก็คือ",message="โมบายล์ (Mobile)")
def nami(event):
    messagebox.showinfo(title="เซนเตอร์ก็คือ",message="ตาหวาน (Tarwann)")
def aita(event):
    messagebox.showinfo(title="เซนเตอร์ก็คือ",message="มิวสิค (Music)")
root = Tk()
root.option_add("*Font","consolas 14")
root.title("BNK48 Who is the center?")
Label(root,bg="pink").pack(fill=X)
Label(root,bg="pink").pack(fill=X)
Label(root,bg="pink").pack(fill=X)
Label(root,text="ใครกันนะ",bg="white").pack(fill=X)
Label(root,text="เซ็นเตอร์ของเพลงๆนี้",bg="white").pack(fill=X)
Label(root,bg="yellow").pack(fill=X)
Label(root,text="รู้สึกยังไงกับโปรแกรมนี้บอกมาได้เลย").pack()
inp = Entry().pack()
kfc = Button(text="Koisuru Fortune Cookie")
kfc.bind('<Button-1>',kfco)
kfc.pack()
namidas = Button(text="Namida Surprise")
namidas.bind('<Button-1>',nami)
namidas.pack()
aitak = Button(text="Aitakatta")
aitak.bind('<Button-1>',aita)
aitak.pack()
menubar = Menu(root)
fileMenu = Menu(menubar,tearoff=0)
fileMenu.add_command(label="New")
fileMenu.add_command(label="Edit")
fileMenu.add_command(label="Play")
fileMenu.add_command(label="Setting")

lifestyle = Menu(menubar,tearoff=0)
lifestyle.add_command(label="Sleep")
lifestyle.add_command(label="Play")
lifestyle.add_command(label="Learn")
menubar.add_cascade(label="JustMenu",menu=fileMenu)
menubar.add_cascade(label="lifestyle",menu=lifestyle)
root.config(menu=menubar)

root.mainloop()
