from tkinter import *
def plus():
    a = int(input("a: "))
    b = int(input("b: "))
    plusy = a + b
    print(plusy)
root = Tk()
root.option_add("*Font","consolas 14")
root.title("Python Flag")
Label(root,bg="blue").pack(fill=X)
Label(root,bg="blue").pack(fill=X)
Label(root,bg="blue").pack(fill=X)
Label(root,text="อยากรู้เหรอว่าเป็นโปรแกรมแนวไหน",bg="white").pack(fill=X)
Label(root,text="อยากรู้ก็จับตาดูเอาไว้นะ",bg="white").pack(fill=X)
Label(root,bg="yellow").pack(fill=X)
Label(root,bg="yellow").pack(fill=X)
Label(root,bg="yellow").pack(fill=X)
Label(root,text="งงมั้ยล่ะครับ ระบุความงงของท่านในช่องนี้ได้").pack()
Entry().pack()
Button(text="Submit",fg="blue",bg="yellow").pack()
menubar = Menu(root)
fileMenu = Menu(menubar,tearoff=0)
fileMenu.add_command(label="New")
fileMenu.add_command(label="Edit")
fileMenu.add_command(label="Play")
fileMenu.add_command(label="Setting")

lifestyle = Menu(menubar,tearoff=0)
lifestyle.add_command(label="Sleep")
lifestyle.add_command(label="Play")
lifestyle.add_command(label="Learn")
menubar.add_cascade(label="JustMenu",menu=fileMenu)
menubar.add_cascade(label="lifestyle",menu=lifestyle)
root.config(menu=menubar)

root.mainloop()
